### ISSUE TITLE
GUI v2: MVP

### ISSUE THREAD

**Issue by apyrgio** [freedomofpress/dangerzone#894]
_Main issue: #885_

Before we start implementing every little detail that we mention in the GUI v2 issues, we should think which are the features that we want to push immediately to our users, and what shortcuts we can take to get faster there. Assuming that the UX makes sense, then the rest of the UI touches will follow.

My suggestion is the following:
- [ ] Start with #886 and just move the burger menu and Dangerzone version to the footer. This way we can then repurpose the space that is now taken by the Dangerzone logo.
- [ ] Continue with #888 and implement as many UI changes as we can within a timebox. The idea is to get a feel for how easy it's to follow the aesthetic of the designs.
- [ ] Continue with #890 and implement it fully. It's quite small and some of the UI elements will be taken by #888.
- [ ] Continue with #892 and implement it fully. We already have a drag-and-drop interface, so the changes will be small.
- [ ] Continue with #893, and heavily base it on #892. This way, we'll get the header and footer for free. We don't need to implement the zebra rows and other visual cues, but we must implement the feature that adds documents to the list while they are converted.

**Comment by harrislapiroff** [comment]
As part of this issue, we'll want to rethink the architecture of the UI, including changes like:

* Possibly using [QML](https://doc.qt.io/qt-6/qmlreference.html) and QtDesigner or Qt Design Studio
* Creating a library of flexible components
